import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.appointment': 'Rendez-vous',
    'nav.legal': 'Mentions légales',
    
    // Common
    'common.contact_us': 'Nous contacter',
    'common.book_appointment': 'Prendre rendez-vous',
    'common.learn_more': 'En savoir plus',
    'common.read_more': 'Lire la suite',
    'common.our_services': 'Nos services',
    'common.our_expertise': 'Notre expertise',
    'common.phone': 'Téléphone',
    'common.email': 'Email',
    'common.address': 'Adresse',
    'common.discover_services': 'Découvrir nos services',
    'common.learn_more_services': 'En savoir plus sur nos services',
    
    // Hero Section
    'hero.title': 'Votre partenaire pour une',
    'hero.title_highlight': 'Performance commerciale durable',
    'hero.subtitle': 'Accompagnement commercial stratégique et opérationnel pour startups et PME innovantes, alliant optimisation commerciale et valorisation d\'une stratégie RSE tangible.',
    'hero.commercial_performance': 'Performance Commerciale',
    'hero.sustainable_development': 'Développement Durable',
    
    // Services Section
    'services.title': 'Nos Services',
    'services.subtitle': 'Des solutions personnalisées pour votre croissance et développement durable',
    'services.commercial_optimization': 'Optimisation commerciale',
    'services.rse_support': 'Accompagnement RSE / Durabilité',
    'services.targeting_title': 'Ciblage / Acquisition',
    'services.targeting_items': '• Optimisation du discours et ciblage commercial\n• Étude de marché\n• Génération de leads externalisée',
    'services.acceleration_title': 'Accélération / Valorisation',
    'services.acceleration_items': '• Levée de fonds\n• Choix d\'outils CRM/ERP\n• Accélération du pipeline',
    'services.optimization_title': 'Optimisation des process',
    'services.optimization_items': '• Audit des outils et process commerciaux\n• Accompagnement au changement\n• Formation des équipes commerciales',
    'services.scope1_title': 'Bilan Emissions Directes - Scope 1',
    'services.scope1_items': '• Analyse Impact Carbone direct\n• Analyse Impact Social\n• Modélisation de scénarios\n• Suivi d\'impacts',
    'services.scope123_title': 'Bilan RSE Complet - Scope 1, 2, 3',
    'services.scope123_items': '• Impacts Carbone et Sociaux Directs/Indirects\n• Double matérialité - impacts et vulnérabilité\n• Scénarios et calcul de ROI\n• Suivi plan d\'action',
    'services.biodiversity_title': 'Bilan Impact Biodiversité',
    'services.biodiversity_items': '• Impacts directs et indirects sur la biodiversité\n• Matrice de matérialité Biodiversité\n• Modélisation de scénarios\n• Suivi d\'impacts',
    'services.stats_startups': 'Startups accompagnées',
    'services.stats_sectors': 'Secteurs d\'expertise',
    'services.stats_experience': 'Années d\'expérience',
    'services.stats_funding': 'Financements cumulés pour un client fidèle',
    
    // Footer
    'footer.company': 'CRM Conseil',
    'footer.description': 'Votre partenaire pour une performance commerciale durable. Alliant excellence commerciale et développement durable.',
    'footer.certification': 'Certifié Développement Durable MIT',
    'footer.contact': 'Contact',
    'footer.consultant': 'Consultante Senior',
    'footer.rights': 'Tous droits réservés.',
    'footer.certifications': 'Certifié MIT Sustainable Strategy • ADEME Partenaire • Miller Heiman Certified',
    
    // Contact Section
    'contact.title': 'Contactez-nous',
    'contact.description': 'Nous vous recontacterons dans les plus brefs délais.',
    'contact.form_name': 'Nom',
    'contact.form_email': 'Email',
    'contact.form_message': 'Message',
    'contact.form_send': 'Envoyer',
    
    // Expertise Section
    'expertise.title': 'Notre Expertise',
    'expertise.subtitle': 'Une approche unique alliant performance commerciale et développement durable',
    'expertise.commercial_years': '15+ ans',
    'expertise.commercial_experience': 'Expérience commerciale',
    'expertise.commercial_desc': 'Direction commerciale, développement business et levées de fonds pour des startups innovantes dans les secteurs GreenTech, DeepTech et HealthTech.',
    'expertise.consulting_years': '8+ ans',
    'expertise.consulting_experience': 'Conseil en durabilité',
    'expertise.consulting_desc': 'Accompagnement RSE et stratégies de développement durable pour entreprises innovantes, avec certifications MIT et ADEME.',
    'expertise.entrepreneurship': 'Entrepreneuriat',
    'expertise.entrepreneurship_desc': 'Expérience entrepreneuriale avec création et développement d\'entreprises dans l\'innovation technologique.',
    'expertise.certifications_title': 'Certifications & Formations',
    'expertise.mit_title': 'MIT Sustainable Strategy',
    'expertise.mit_desc': 'Certification en stratégie de développement durable par le Massachusetts Institute of Technology',
    'expertise.sales_title': 'Miller Heiman Sales Process',
    'expertise.sales_desc': 'Certification en processus de vente stratégique et gestion de pipeline commercial',
    'expertise.mba_title': 'MBA Management & Strategy',
    'expertise.mba_desc': 'Master en administration des affaires, spécialisation management et stratégie d\'entreprise',
    'expertise.methodologies': 'Méthodologies & Outils',
    'expertise.commercial_optimization': 'Optimisation Commerciale',
    'expertise.rse_biodiversity': 'RSE & Biodiversité',
    'expertise.unique_approach': 'Notre Approche Unique',
    'expertise.performance_sustainability': 'Performance & Durabilité',
    'expertise.performance_desc': 'Nous combinons excellence commerciale et stratégies durables pour une croissance responsable.',
    'expertise.sector_expertise': 'Expertise Sectorielle',
    'expertise.sector_desc': 'Spécialisation dans l\'innovation technologique : GreenTech, DeepTech, HealthTech et Digital.',
    'expertise.recognized_certifications': 'Certifications Reconnues',
    'expertise.certifications_desc': 'Formations MIT, ADEME et Miller Heiman pour une expertise de pointe.',
    'expertise.discover_about': 'Découvrir notre parcours',
    
    // Portfolio Section
    'portfolio.title': 'Nos Références',
    'portfolio.subtitle': 'Plus de 60 startups accompagnées dans leur développement commercial et leur stratégie RSE',
    'portfolio.greentech': 'GreenTech',
    'portfolio.greentech_desc': 'Technologies vertes et solutions environnementales',
    'portfolio.deeptech': 'DeepTech',
    'portfolio.deeptech_desc': 'Intelligence artificielle et technologies de pointe',
    'portfolio.healthtech': 'HealthTech',
    'portfolio.healthtech_desc': 'Technologies médicales et santé digitale',
    'portfolio.digital': 'Digital & Tech',
    'portfolio.digital_desc': 'Solutions numériques et transformation digitale',
    'portfolio.partners': 'Nos Partenaires',
    
    // Services Page - Additional elements
    'services.page_title': 'Services - CRM Conseil | Accompagnement Commercial & RSE pour PME',
    'services.page_description': 'Découvrez nos services d\'accompagnement commercial et RSE : bilan carbone, stratégie commerciale, conseil développement durable. Expertise certifiée pour startups et PME à Nice, Monaco, Cannes.',
    'services.page_keywords': 'services conseil commercial, bilan carbone PME, accompagnement RSE, stratégie commerciale, développement durable entreprise, consultant Nice Monaco',
    'services.quote': '"Chez CRM Conseil, nous sommes profondément convaincus que <strong class="text-sustainable font-semibold">l\'alignement de la performance commerciale avec une démarche concrète de durabilité</strong> est la seule voie viable pour l\'avenir."',
    'services.performance_sustainability': 'Performance et durabilité commerciale',
    'services.ecological_sustainability': 'Durabilité écologique et sociétale',
    'services.discover_services': 'Découvrez nos services',
    'services.commercial_optimization_missions': 'Missions d\'optimisation commerciale',
    'services.rse_support_bilans': 'Accompagnements et Bilans RSE',
    'services.commercial_intro_1': 'Moins de 40 % du temps des commerciaux est dédié à la vente. CRM Conseil aide les startups et PME à éliminer les blocages, optimiser leurs processus de vente et maximiser leur efficacité commerciale. Simplifiez vos outils, perfectionnez vos pitchs et atteignez des résultats durables.',
    'services.commercial_intro_2': 'Notre approche combine analyse des performances actuelles, formation pratique et accompagnement sur le terrain pour transformer vos équipes commerciales en forces de vente performantes. Nos missions sont courtes et pratiques pour respecter les budgets et le temps rapide de nos clients startups et PMEs. Vous récupérez des éléments utilisables immédiatement pour continuer votre prospection en toute autonomie.',
    'services.process_optimization_title': 'Optimisation des process commerciaux',
    'services.process_optimization_desc': 'Analyse et restructuration de vos processus de vente, amélioration du cycle commercial, accompagnement lors de RDV clients stratégiques, optimisation des argumentaires et méthodes de prospection pour maximiser votre efficacité commerciale.',
    'services.tools_configuration_title': 'Choix et Configuration d\'outils de pilotage (CRM/ERP)',
    'services.tools_configuration_desc': 'Sélection et configuration d\'outils (CRM/ERP) adaptés à vos besoins, budget et perspectives de croissance. CRM Conseil vous oriente vers les outils les plus scalable pour éviter d\'avoir à multiplier ou changer d\'outils au fil de votre développement. Nous formons vos équipes, configurons vos tableaux de bord de pilotage commercial.',
    'services.lead_generation_title': 'Générations de leads B2B',
    'services.lead_generation_desc': 'Stratégies de prospection multicanales, qualification de leads, mise en place de campagnes ciblées et accompagnement dans la génération de prospects qualifiés pour développer votre portefeuille clients.',
    'services.valorization_title': 'Valorisation commerciale pour levée de fonds',
    'services.valorization_desc': 'Préparation de pitchs investisseurs, valorisation de votre modèle économique, coaching pour les présentations et optimisation de votre approche commerciale pour séduire les investisseurs.',
    'services.what_we_bring': 'Ce que nous vous apportons:',
    'services.phase_1_title': 'Phase 1 – Ciblage / Acquisition',
    'services.phase_1_subtitle': 'Startups early stage',
    'services.conversion_increase': 'd\'augmentation du taux de conversion prospects → clients',
    'services.cycle_acceleration': 'd\'accélération du cycle de vente',
    'services.qualified_meetings': 'de rendez-vous qualifiés obtenus',
    'services.phase_2_title': 'Phase 2 – Accélération / Valorisation',
    'services.phase_2_subtitle': 'Startups & PME établies',
    'services.pipeline_value_increase': 'd\'augmentation de la valeur du pipeline',
    'services.commercial_efficiency': 'd\'efficacité commerciale des équipes',
    'services.success_rate': 'de taux de succès en levée de fonds',
    'services.deliverables': 'Nos livrables',
    'services.deliverable_1': 'Slides de présentation commerciale révisée',
    'services.deliverable_2': 'Slides Deck investisseur révisé',
    'services.deliverable_3': 'Outils CRM/ERP implémentés et personnalisés',
    'services.deliverable_4': 'Questionnaire de qualification et process de vente optimisé',
    'services.deliverable_5': 'Listes de leads qualifiés',
    'services.deliverable_6': 'Pipeline et marché cible valorisé et sécurisé',
    'services.pricing_commercial': '1 à 8 JH ~ 950€ - 7,600€',
    'services.ready_transform': 'Prêt à transformer votre entreprise ?',
    'services.transform_desc': 'Réservez votre consultation gratuite de 30 minutes pour discuter de vos besoins et découvrir comment nous pouvons accompagner votre entreprise.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.appointment': 'Book Appointment',
    'nav.legal': 'Legal Notice',
    
    // Common
    'common.contact_us': 'Contact us',
    'common.book_appointment': 'Book appointment',
    'common.learn_more': 'Learn more',
    'common.read_more': 'Read more',
    'common.our_services': 'Our services',
    'common.our_expertise': 'Our expertise',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    'common.discover_services': 'Discover our services',
    'common.learn_more_services': 'Learn more about our services',
    
    // Hero Section
    'hero.title': 'Your partner for',
    'hero.title_highlight': 'Sustainable Commercial Performance',
    'hero.subtitle': 'Strategic and operational commercial support for innovative startups and SMEs, combining commercial optimization and enhancement of a tangible CSR strategy.',
    'hero.commercial_performance': 'Commercial Performance',
    'hero.sustainable_development': 'Sustainable Development',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Customized solutions for your growth and sustainable development',
    'services.commercial_optimization': 'Commercial optimization',
    'services.rse_support': 'CSR / Sustainability Support',
    'services.targeting_title': 'Targeting / Acquisition',
    'services.targeting_items': '• Commercial speech and targeting optimization\n• Market research\n• Outsourced lead generation',
    'services.acceleration_title': 'Acceleration / Valorization',
    'services.acceleration_items': '• Fundraising\n• CRM/ERP tools selection\n• Pipeline acceleration',
    'services.optimization_title': 'Process Optimization',
    'services.optimization_items': '• Commercial tools and process audit\n• Change management\n• Sales team training',
    'services.scope1_title': 'Direct Emissions Assessment - Scope 1',
    'services.scope1_items': '• Direct Carbon Impact Analysis\n• Social Impact Analysis\n• Scenario modeling\n• Impact tracking',
    'services.scope123_title': 'Complete CSR Assessment - Scope 1, 2, 3',
    'services.scope123_items': '• Direct/Indirect Carbon and Social Impacts\n• Double materiality - impacts and vulnerability\n• Scenarios and ROI calculation\n• Action plan monitoring',
    'services.biodiversity_title': 'Biodiversity Impact Assessment',
    'services.biodiversity_items': '• Direct and indirect impacts on biodiversity\n• Biodiversity materiality matrix\n• Scenario modeling\n• Impact tracking',
    'services.stats_startups': 'Startups supported',
    'services.stats_sectors': 'Expertise sectors',
    'services.stats_experience': 'Years of experience',
    'services.stats_funding': 'Cumulative funding for a loyal client',
    
    // Footer
    'footer.company': 'CRM Conseil',
    'footer.description': 'Your partner for sustainable commercial performance. Combining commercial excellence and sustainable development.',
    'footer.certification': 'MIT Sustainable Development Certified',
    'footer.contact': 'Contact',
    'footer.consultant': 'Senior Consultant',
    'footer.rights': 'All rights reserved.',
    'footer.certifications': 'MIT Sustainable Strategy Certified • ADEME Partner • Miller Heiman Certified',
    
    // Contact Section
    'contact.title': 'Contact us',
    'contact.description': 'We will get back to you as soon as possible.',
    'contact.form_name': 'Name',
    'contact.form_email': 'Email',
    'contact.form_message': 'Message',
    'contact.form_send': 'Send',
    
    // Expertise Section
    'expertise.title': 'Our Expertise',
    'expertise.subtitle': 'A unique approach combining commercial performance and sustainable development',
    'expertise.commercial_years': '15+ years',
    'expertise.commercial_experience': 'Commercial experience',
    'expertise.commercial_desc': 'Commercial management, business development and fundraising for innovative startups in GreenTech, DeepTech and HealthTech sectors.',
    'expertise.consulting_years': '8+ years',
    'expertise.consulting_experience': 'Sustainability consulting',
    'expertise.consulting_desc': 'CSR support and sustainable development strategies for innovative companies, with MIT and ADEME certifications.',
    'expertise.entrepreneurship': 'Entrepreneurship',
    'expertise.entrepreneurship_desc': 'Entrepreneurial experience with creation and development of companies in technological innovation.',
    'expertise.certifications_title': 'Certifications & Training',
    'expertise.mit_title': 'MIT Sustainable Strategy',
    'expertise.mit_desc': 'Sustainable development strategy certification by the Massachusetts Institute of Technology',
    'expertise.sales_title': 'Miller Heiman Sales Process',
    'expertise.sales_desc': 'Strategic sales process and commercial pipeline management certification',
    'expertise.mba_title': 'MBA Management & Strategy',
    'expertise.mba_desc': 'Master in Business Administration, specializing in management and business strategy',
    'expertise.methodologies': 'Methodologies & Tools',
    'expertise.commercial_optimization': 'Commercial Optimization',
    'expertise.rse_biodiversity': 'CSR & Biodiversity',
    'expertise.unique_approach': 'Our Unique Approach',
    'expertise.performance_sustainability': 'Performance & Sustainability',
    'expertise.performance_desc': 'We combine commercial excellence and sustainable strategies for responsible growth.',
    'expertise.sector_expertise': 'Sector Expertise',
    'expertise.sector_desc': 'Specialization in technological innovation: GreenTech, DeepTech, HealthTech and Digital.',
    'expertise.recognized_certifications': 'Recognized Certifications',
    'expertise.certifications_desc': 'MIT, ADEME and Miller Heiman training for cutting-edge expertise.',
    'expertise.discover_about': 'Discover our journey',
    
    // Portfolio Section
    'portfolio.title': 'Our References',
    'portfolio.subtitle': 'More than 60 startups supported in their commercial development and CSR strategy',
    'portfolio.greentech': 'GreenTech',
    'portfolio.greentech_desc': 'Green technologies and environmental solutions',
    'portfolio.deeptech': 'DeepTech',
    'portfolio.deeptech_desc': 'Artificial intelligence and cutting-edge technologies',
    'portfolio.healthtech': 'HealthTech',
    'portfolio.healthtech_desc': 'Medical technologies and digital health',
    'portfolio.digital': 'Digital & Tech',
    'portfolio.digital_desc': 'Digital solutions and digital transformation',
    'portfolio.partners': 'Our Partners',
    
    // About Page - Complete translations
    'about.page_title': 'About Us - CRM Conseil | Commercial Performance & CSR Expertise',
    'about.our_story': 'Our Story',
    'about.story_desc_1': 'CRM Conseil was created in 2014 with the objective of applying large account commercial methods to growing startups. This innovative approach allowed young companies to efficiently structure their commercial development.',
    'about.story_desc_2': 'Around 2018, we naturally evolved towards supporting companies oriented towards sustainable development and greentech, anticipating tomorrow\'s challenges. This transition reflected our conviction that responsible companies would be tomorrow\'s leaders.',
    'about.story_desc_3': 'Today, after 10 years of evolution, we have become specialists in commercial support for companies that place sustainability at the heart of their growth strategy.',
    'about.meet_team': 'Book a consultation',
    'about.our_values': 'Our Values',
    'about.trust': 'Trust',
    'about.trust_desc': 'We build lasting partnerships based on transparency, honesty and mutual respect.',
    'about.sustainability': 'Sustainability', 
    'about.sustainability_desc': 'We support companies in their sustainable transformation for responsible and lasting growth.',
    'about.excellence': 'Excellence',
    'about.excellence_desc': 'We are committed to delivering concrete and measurable results, optimizing every aspect of your commercial strategy.',
    'about.our_expertise': 'Our Expertise',
    'about.key_stats_title': 'Our Expertise',
    'about.stat_startups': 'Startups and innovative SMEs supported',
    'about.stat_growth': 'Increase in commercial results', 
    'about.stat_sectors': 'Expertise sectors',
    'about.stat_funding': 'Cumulative funding for a loyal client',
    'about.sectors_title': 'Activity Sectors',
    'about.greentech': 'GreenTech',
    'about.greentech_desc': 'Support for innovative companies in green technologies and sustainable development.',
    'about.healthtech': 'HealthTech', 
    'about.healthtech_desc': 'Commercial solutions dedicated to health technology companies and innovative medical devices.',
    'about.industry': 'Industry',
    'about.industry_desc': 'Commercial process optimization and digital transformation for modern industrial actors.',
    'about.dev_ai': 'Dev-AI',
    'about.dev_ai_desc': 'Commercial strategies for software development and artificial intelligence companies.',
    'about.certifications_title': 'Our Certifications & Partnerships',
    'about.mit_cert': 'MIT Certification',
    'about.mit_cert_desc': 'Sustainable Strategy Design',
    'about.ademe_partner': 'ADEME', 
    'about.ademe_partner_desc': 'Official Partner',
    'about.pacte_national': 'National Pact',
    'about.pacte_national_desc': 'Energy Transition',
    'about.company_history': 'Our Story',
    'about.evolution_title': 'Our Evolution',
    'about.year_2014': '2014',
    'about.year_2014_title': 'Creation of CRM Conseil',
    'about.year_2014_desc': 'Foundation of the company with a focus on commercial performance of startups using large account methods.',
    'about.year_2018': '2018', 
    'about.year_2018_title': 'Turn towards Sustainable Development',
    'about.year_2018_desc': 'Natural evolution towards supporting companies oriented towards sustainable development and greentech.',
    'about.year_2019': '2019',
    'about.year_2019_title': 'Fundraising Expertise',
    'about.year_2019_desc': 'Development of our expertise in preparation and support for fundraising.',
    'about.year_2024': '2024',
    'about.year_2024_title': 'CSR & Sustainability Specialization', 
    'about.year_2024_desc': 'Specialization in supporting CSR transformations and sustainability strategies.',
    'about.method_title': 'Our field support method',
    'about.method_subtitle': 'We work hand in hand with your teams for concrete actions and immediately measurable results.',
    'about.method_approach': 'At CRM Conseil, we don\'t just give advice: we work concretely with you in the field to optimize your sales.',
    'about.our_difference': 'Our difference?',
    'about.difference_desc_1': 'We create your slides, accompany you to meetings, configure your tools and train your teams on their real projects.',
    'about.difference_desc_2': '100% operational support for immediate results.',
    'about.no_theory_title': 'Finished with theoretical advice without practical implementation!',
    'about.no_theory_desc': 'CRM Conseil integrates with your team to transform your commercial challenges into concrete successes: personalized sales materials, field support and tool configuration adapted to your needs.',
    'about.methods_title': 'Our Methods',
    'about.external_audit': 'External audit',
    'about.external_audit_step_1': '1. Neutral analysis of your processes',
    'about.external_audit_step_2': '2. Optimization proposals',
    'about.external_audit_step_3': '3. Implementation support',
    'about.external_audit_step_4': '4. Impact monitoring',
    'about.tools_config': 'Practical tool configuration',
    'about.tools_config_step_1': '1. Analysis of your existing tools',
    'about.tools_config_step_2': '2. Proposals for complementary tools or usage optimizations',
    'about.tools_config_step_3': '3. Tool configuration',
    'about.tools_config_step_4': '4. Team training and usage monitoring',
    'about.commercial_materials': 'Creation of commercial materials',
    'about.commercial_materials_step_1': '1. Analysis of your existing materials',
    'about.commercial_materials_step_2': '2. Optimization proposals',
    'about.commercial_materials_step_3': '3. Co-production of new materials',
    'about.commercial_materials_step_4': '4. Material testing in client meetings',
    'about.team_training': 'Team training and coaching',
    'about.team_training_step_1': '1. Evaluation of skills and methods of commercial teams',
    'about.team_training_step_2': '2. Proposal of coaching or specific training for team challenges',
    'about.team_training_step_3': '3. Training delivery',
    'about.team_training_step_4': '4. Field impact monitoring on sales',
    'about.carbon_assessment': 'Carbon Assessment',
    'about.carbon_assessment_step_1': '1. Analysis of existing carbon impacts',
    'about.carbon_assessment_step_2': '2. Corporate brainstorming of more sustainable changes',
    'about.carbon_assessment_step_3': '3. Modeling and analysis of impacts and ROI of each scenario',
    'about.carbon_assessment_step_4': '4. Implementation monitoring and KPI impact',
    'about.biodiversity_assessment': 'Biodiversity Assessment',
    'about.biodiversity_assessment_step_1': '1. Analysis of existing biodiversity impact',
    'about.biodiversity_assessment_step_2': '2. Co-construction of an evolution roadmap',
    'about.biodiversity_assessment_step_3': '3. Modeling and analysis of impacts and ROI of each option',
    'about.biodiversity_assessment_step_4': '4. Implementation monitoring and KPI impacts',
    'about.excellence_operational': 'Operational Excellence',
    'about.excellence_operational_desc': 'We are committed to delivering concrete and measurable results, optimizing every aspect of your commercial strategy.',
    'about.innovation_continuous': 'Continuous Innovation',
    'about.innovation_continuous_desc': 'We integrate the latest technologies and methodologies to give you a sustainable competitive advantage.',
    'about.impact_sustainable': 'Sustainable Impact',
    'about.impact_sustainable_desc': 'Beyond commercial performance, we help you build a responsible and sustainable company.',

    // Services Page - Additional elements  
    'services.page_title': 'Our Services - CRM Conseil | Commercial Consulting & CSR Support',
    'services.page_description': 'Discover our commercial consulting services, CSR support, carbon footprint for SMEs. Personalized support for sustainable commercial development in Nice, Monaco, Cannes.',
    'services.page_keywords': 'commercial consulting services, SME carbon footprint, CSR support, commercial strategy, sustainable business development, Nice Monaco consultant',
    'services.quote': '"At CRM Conseil, we are deeply convinced that <strong class="text-sustainable font-semibold">aligning commercial performance with a concrete sustainability approach</strong> is the only viable path for the future."',
    'services.performance_sustainability': 'Commercial performance and sustainability',
    'services.ecological_sustainability': 'Ecological and societal sustainability',
    'services.discover_services': 'Discover our services',
    'services.commercial_optimization_missions': 'Commercial optimization missions',
    'services.rse_support_bilans': 'CSR support and assessments',
    'services.commercial_intro_1': 'Less than 40% of sales representatives\' time is dedicated to selling. CRM Conseil helps startups and SMEs eliminate bottlenecks, optimize their sales processes and maximize their commercial efficiency. Simplify your tools, perfect your pitches and achieve sustainable results.',
    'services.commercial_intro_2': 'Our approach combines analysis of current performance, practical training and field support to transform your sales teams into high-performing sales forces. Our missions are short and practical to respect the budgets and fast pace of our startup and SME clients. You get immediately usable elements to continue your prospecting autonomously.',
    'services.process_optimization_title': 'Commercial process optimization',
    'services.process_optimization_desc': 'Analysis and restructuring of your sales processes, improvement of the commercial cycle, support during strategic client meetings, optimization of sales pitches and prospecting methods to maximize your commercial efficiency.',
    'services.tools_configuration_title': 'Selection and Configuration of management tools (CRM/ERP)',
    'services.tools_configuration_desc': 'Selection and configuration of tools (CRM/ERP) adapted to your needs, budget and growth prospects. CRM Conseil guides you towards the most scalable tools to avoid having to multiply or change tools as you develop. We train your teams and configure your commercial management dashboards.',
    'services.lead_generation_title': 'B2B lead generation',
    'services.lead_generation_desc': 'Multi-channel prospecting strategies, lead qualification, implementation of targeted campaigns and support in generating qualified prospects to develop your client portfolio.',
    'services.valorization_title': 'Commercial valorization for fundraising',
    'services.valorization_desc': 'Preparation of investor pitches, valorization of your business model, coaching for presentations and optimization of your commercial approach to seduce investors.',
    'services.what_we_bring': 'What we bring you:',
    'services.phase_1_title': 'Phase 1 – Targeting / Acquisition',
    'services.phase_1_subtitle': 'Early stage startups',
    'services.conversion_increase': 'increase in prospect → client conversion rate',
    'services.cycle_acceleration': 'acceleration of the sales cycle',
    'services.qualified_meetings': 'qualified meetings obtained',
    'services.phase_2_title': 'Phase 2 – Acceleration / Valorization',
    'services.phase_2_subtitle': 'Established startups & SMEs',
    'services.pipeline_value_increase': 'increase in pipeline value',
    'services.commercial_efficiency': 'team commercial efficiency',
    'services.success_rate': 'fundraising success rate',
    'services.deliverables': 'Our deliverables',
    'services.deliverable_1': 'Revised commercial presentation slides',
    'services.deliverable_2': 'Revised investor deck slides',
    'services.deliverable_3': 'Implemented and customized CRM/ERP tools',
    'services.deliverable_4': 'Qualification questionnaire and optimized sales process',
    'services.deliverable_5': 'Qualified lead lists',
    'services.deliverable_6': 'Valued and secured pipeline and target market',
    'services.pricing_commercial': '1 to 8 person-days ~ €950 - €7,600',
    'services.ready_transform': 'Ready to transform your business?',
    'services.transform_desc': 'Book your free 30-minute consultation to discuss your needs and discover how we can support your company.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  useEffect(() => {
    const path = window.location.pathname;
    if (path.startsWith('/en')) {
      setLanguage('en');
    } else {
      setLanguage('fr');
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};