import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.appointment': 'Rendez-vous',
    'nav.legal': 'Mentions légales',
    
    // Common
    'common.contact_us': 'Nous contacter',
    'common.book_appointment': 'Prendre rendez-vous',
    'common.learn_more': 'En savoir plus',
    'common.read_more': 'Lire la suite',
    'common.our_services': 'Nos services',
    'common.our_expertise': 'Notre expertise',
    'common.phone': 'Téléphone',
    'common.email': 'Email',
    'common.address': 'Adresse',
    'common.discover_services': 'Découvrir nos services',
    'common.learn_more_services': 'En savoir plus sur nos services',
    
    // Hero Section - Optimized with keywords
    'hero.title': 'Et si vos engagements de Durabilité devenaient l\'accélérateur de vos résultats commerciaux ?',
    'hero.subtitle': '',
    'hero.description': 'CRM Conseil unit optimisation commerciale et transition durable pour redéfinir avec ses clients, startups, TPEs et PMEs, leur stratégie de croissance responsable.\nTransformons vos actions RSE en véritables leviers de performance et compétitivité.',
    'hero.commercial_performance': 'Optimisation Commerciale',
    'hero.sustainable_development': 'Stratégie RSE & Bilan GES',
    
    // Services Section - Optimized with keywords
    'services.title': 'Nos Services',
    'services.subtitle': 'Votre partenaire pour une Optimisation commerciale Durable',
    'services.commercial_optimization': 'Optimisation commerciale',
    'services.rse_support': 'Transition durable / RSE',
    'services.targeting_title': 'Démarrage / Acquisition clients',
    'services.targeting_items': '• Optimisation du discours et ciblage commercial\n• Co-optimisation des supports commerciaux\n• Accès marché / Génération de leads externalisée',
    'services.acceleration_title': 'Accélération / Levée de fonds',
    'services.acceleration_items': '• Design du Deck Investisseur\n• Optimisation KPIs, marchés cible, avantages\n• Coaching dirigeant sur pitch Investisseurs',
    'services.optimization_title': 'Optimisation process commerciaux',
    'services.optimization_items': '• Audit et Optimisation process de vente\n• Choix d\'outils CRM/ERP/IA\n• Formation des équipes à des méthodes de vente',
    'services.scope1_title': 'Bilan GES Durabilité / Bilan Carbone®',
    'services.scope1_items': '• Analyse des émissions carbone\n• Analyse des risques climatiques\n• Plan de transition durable',
    'services.scope123_title': 'Accompagnement des équipes aux actions durables',
    'services.scope123_items': '• Suivi de la stratégie RSE\n• Formation aux actions durables\n• Accompagnement au changement',
    'services.biodiversity_title': 'Valorisation commerciale de la démarche RSE',
    'services.biodiversity_items': '• Modélisation ROI pluriannuel\n• Repositionnement produits\n• Génération de leads sur nouveaux marchés',
    'services.stats_startups': 'Startups/PMEs accompagnées',
    'services.stats_sectors': "d'impact commercial d'une démarche RSE",
    'services.stats_experience': 'taux de succès à la levée de fonds',
    'services.stats_funding': 'financement cumulés optimisés',
    'services.ready_transform': 'Prêt à transformer votre entreprise avec performance et durabilité ?',
    'services.transform_desc': 'Réservez votre consultation gratuite de 30 minutes pour discuter de vos besoins en optimisation commerciale, business development et stratégie RSE.',
    
    // Contact form confirmation messages
    'contact.success_toast_title': 'Message envoyé avec succès !',
    'contact.success_toast_description': 'Merci pour votre message. Nous vous répondrons dans les plus brefs délais.',
    'contact.error_toast_title': 'Erreur d\'envoi',
    'contact.error_toast_description': 'Une erreur s\'est produite lors de l\'envoi de votre message. Veuillez réessayer ou nous contacter directement.',
    'contact.error_validation_title': 'Champs obligatoires manquants',
    'contact.error_validation_description': 'Veuillez remplir tous les champs obligatoires.',
    'contact.sending': 'Envoi en cours...',
    
    // Footer
    'footer.company': 'CRM Conseil',
    'footer.description': 'Votre partenaire pour une performance commerciale durable. Alliant excellence commerciale, génération de leads et développement durable.',
    'footer.certification': 'Certifié Développement Durable MIT',
    'footer.contact': 'Contact',
    'footer.consultant': 'Consultante Senior Performance & RSE',
    'footer.rights': 'Tous droits réservés.',
    'footer.certifications': 'Certifié MIT Sustainable Strategy • Miller Heiman Certified',
    
    // Contact Section
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Parlons de votre projet d\'optimisation commerciale et de développement durable',
    'contact.description': 'Nous vous recontacterons dans les plus brefs délais.',
    'contact.phone_label': 'Téléphone',
    'contact.address_label': 'Zone d\'intervention', 
    'contact.address_value': 'Nice, Cannes, Monaco et environs',
    'contact.service_area': 'Zone d\'intervention',
    'contact.service_area_value': 'Monaco • France • Europe • International',
    'contact.consultation_label': 'Consultation gratuite',
    'contact.consultation': 'Diagnostic initial et recommandations personnalisées',
    'contact.commercial_card': 'Optimisation Commerciale',
    'contact.commercial_desc': 'Performance & Business Development',  
    'contact.rse_card': 'RSE / Développement Durable',
    'contact.rse_desc': 'Bilan GES & Stratégie RSE',
    'contact.form_name': 'Nom',
    'contact.form_full_name': 'Nom complet *',
    'contact.form_name_placeholder': 'Votre nom',
    'contact.form_email': 'Email *',
    'contact.form_email_placeholder': 'votre@email.com',
    'contact.form_company': 'Entreprise *',
    'contact.form_company_placeholder': 'Nom de votre entreprise',
    'contact.form_service': 'Service d\'intérêt',
    'contact.form_service_select': 'Sélectionnez un service',
    'contact.form_service_conseil_commercial': 'Conseil et Optimisation commerciale',
    'contact.form_service_rse_bilan': 'Accompagnement RSE / Bilan Carbone®',
    'contact.form_message': 'Message *',
    'contact.form_message_placeholder': 'Décrivez votre projet d\'optimisation commerciale ou de stratégie RSE...',
    'contact.form_send': 'Envoyer le message',
    'contact.form_required': '* Champs obligatoires',
    'contact.success_title': 'Message envoyé !',
    'contact.success_message': 'Nous vous recontacterons dans les plus brefs délais pour votre projet.',
    
    // Expertise Section
    'expertise.title': 'Notre Expertise',
    'expertise.subtitle': 'Depuis 2014, CRM Conseil accompagne la croissance de startups et TPE/PMEs engagées dans l\'amélioration de leurs résultats commerciaux. Passez dès aujourd\'hui à l\'étape d\'après, en faisant de votre transition durable un levier d\'accélération commerciale pour l\'avenir.',
    'expertise.commercial_years': '26+ ans',
    'expertise.commercial_experience': 'Développement et optimisation commerciaux',
    'expertise.commercial_desc': '• Vente et pilotage d\'équipes commerciales France et International\n• Optimisation commerciale terrain de startups et TPE/PMEs\n• Préparation pratique de la levée de fonds dans les secteurs Greentech, Deeptech, Agritech, Healthtech et Telecom\n• Optimisation commerciale secteur Tourisme.',
    'expertise.consulting_years': '5+ ans',
    'expertise.consulting_experience': 'Conseil en durabilité & stratégie RSE',
    'expertise.consulting_desc': 'Accompagnement RSE et valorisation de stratégies de développement durable',
    'expertise.entrepreneurship': 'Entrepreneuriat & Innovation',
    'expertise.entrepreneurship_desc': 'Plusieurs expériences entrepreneuriales avec création et gestion d\'entreprises dans le numérique, le tourisme et le conseil, avec une démarche systématique de durabilité.',
    'expertise.certifications_title': 'Certifications & Formations',
    'expertise.mit_title': 'MIT Sustainable Strategy',
    'expertise.mit_desc': 'Certification en stratégie de développement durable par le Massachusetts Institute of Technology',
    'expertise.ademe_title': 'ADEME Bilan Carbone®',
    'expertise.ademe_desc': 'Certification de l\'ABC pour réaliser des Bilans Carbone® règlementaires.',
    'expertise.sales_title': 'Miller Heiman Sales Process',
    'expertise.sales_desc': 'Certification à la méthode Miller Heiman de Vente stratégique auprès de Grands comptes',
    'expertise.mba_title': 'FIU/SKEMA Bachelor of Business Administration',
    'expertise.mba_desc': 'Bachelor en gestion d\'entreprise, marketing et commerce international de la Florida International University, et de SKEMA France.',
    'expertise.methodologies': 'Méthodologies & Outils',
    'expertise.commercial_optimization': 'Optimisation Commerciale',
    'expertise.rse_biodiversity': 'RSE, Biodiversité & Bilan Carbone®',
    'expertise.unique_approach': 'Notre Approche Unique',
    'expertise.performance_sustainability': 'Performance & Durabilité',
    'expertise.performance_desc': 'Nous combinons excellence commerciale et stratégies durables pour une croissance responsable.',
    'expertise.sector_expertise': 'Expertise Sectorielle Innovation',
    'expertise.sector_desc': 'Spécialisation dans l\'innovation technologique : GreenTech, DeepTech, HealthTech et Digital.',
    'expertise.recognized_certifications': 'Certifications Reconnues',
    'expertise.certifications_desc': 'Formations MIT, Bilan Carbone® et Miller Heiman pour une expertise de pointe en performance commerciale et durabilité.',
    'expertise.discover_about': 'Découvrir notre parcours',
    
    // Portfolio Section
    'portfolio.title': 'Nos Références',
    'portfolio.subtitle': 'Plus de 100 startups et PMEs accompagnées dans leur optimisation commerciale et stratégie RSE',
    'portfolio.greentech': 'Greentech',
    'portfolio.greentech_desc': '',
    'portfolio.deeptech': 'Deeptech',
    'portfolio.deeptech_desc': '',
    'portfolio.healthtech': 'Devtech',
    'portfolio.healthtech_desc': '',
    'portfolio.digital': 'Tourisme',
    'portfolio.digital_desc': '',
    'portfolio.partners': 'Nos partenaires',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.appointment': 'Book Appointment',
    'nav.legal': 'Legal Notice',
    
    // Common
    'common.contact_us': 'Contact us',
    'common.book_appointment': 'Book appointment',
    'common.learn_more': 'Learn more',
    'common.read_more': 'Read more',
    'common.our_services': 'Our services',
    'common.our_expertise': 'Our expertise',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    'common.discover_services': 'Discover our services',
    'common.learn_more_services': 'Learn more about our services',
    
    // Hero Section - Optimized with keywords
    'hero.title': 'What if your Sustainability commitments became the accelerator for your business results?',
    'hero.subtitle': '',
    'hero.description': 'CRM Conseil combines commercial optimization and sustainable transition to redefine with its clients, startups, VSEs and SMEs, their responsible growth strategy.\nLet\'s transform your CSR actions into real performance and competitiveness drivers.',
    'hero.commercial_performance': 'Commercial Optimization',
    'hero.sustainable_development': 'CSR Strategy & GHG Assessment',
    
    // Services Section - Optimized with keywords
    'services.title': 'Our Services',
    'services.subtitle': 'Your partner for Sustainable Commercial Optimization',
    'services.commercial_optimization': 'Commercial Optimization',
    'services.rse_support': 'Sustainable Transition / CSR',
    'services.targeting_title': 'Startup / Customer Acquisition',
    'services.targeting_items': '• Commercial speech and targeting optimization\n• Co-optimization of commercial materials\n• Market access / Outsourced lead generation',
    'services.acceleration_title': 'Acceleration / Fundraising',
    'services.acceleration_items': '• Investor Deck Design\n• KPIs, target markets, advantages optimization\n• Executive coaching on investor pitch',
    'services.optimization_title': 'Commercial Process Optimization',
    'services.optimization_items': '• Sales process audit and optimization\n• CRM/ERP/AI tools selection\n• Sales team training on sales methodologies',
    'services.scope1_title': 'GHG Sustainability / Carbon® Assessment',
    'services.scope1_items': '• Carbon emissions analysis\n• Climate risk analysis\n• Sustainable transition plan',
    'services.scope123_title': 'Team Support for Sustainable Actions',
    'services.scope123_items': '• CSR strategy monitoring\n• Sustainable actions training\n• Change management support',
    'services.biodiversity_title': 'Commercial Valorization of CSR Approach',
    'services.biodiversity_items': '• Multi-year ROI modeling\n• Product repositioning\n• Lead generation on new markets',
    'services.stats_startups': 'Startups/SMEs supported',
    'services.stats_sectors': 'commercial impact of a CSR approach',
    'services.stats_experience': 'fundraising success rate',
    'services.stats_funding': 'optimized cumulative funding',
    'services.ready_transform': 'Ready to transform your business with performance and sustainability?',
    'services.transform_desc': 'Book your free 30-minute consultation to discuss your commercial optimization, business development and CSR strategy needs.',
    
    // Footer
    'footer.company': 'CRM Conseil',
    'footer.description': 'Your partner for sustainable commercial performance. Combining commercial excellence, lead generation and sustainable development.',
    'footer.certification': 'MIT Sustainable Development Certified',
    'footer.contact': 'Contact',
    'footer.consultant': 'Senior Performance & CSR Consultant',
    'footer.rights': 'All rights reserved.',
    'footer.certifications': 'MIT Sustainable Strategy Certified • Miller Heiman Certified',
    
    // Contact Section
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Let\'s talk about your commercial optimization and sustainable development project',
    'contact.description': 'We will contact you as soon as possible.',
    'contact.phone_label': 'Phone',
    'contact.address_label': 'Service area', 
    'contact.address_value': 'Nice, Cannes, Monaco and surroundings',
    'contact.service_area': 'Service Area',
    'contact.service_area_value': 'Monaco • France • Europe • International',
    'contact.consultation_label': 'Free consultation',
    'contact.consultation': 'Initial diagnosis and personalized recommendations',
    'contact.commercial_card': 'Commercial Optimization',
    'contact.commercial_desc': 'Performance & Business Development',  
    'contact.rse_card': 'CSR / Sustainable Development',
    'contact.rse_desc': 'GHG Assessment & CSR Strategy',
    'contact.form_name': 'Name',
    'contact.form_full_name': 'Full Name *',
    'contact.form_name_placeholder': 'Your name',
    'contact.form_email': 'Email *',
    'contact.form_email_placeholder': 'your@email.com',
    'contact.form_company': 'Company *',
    'contact.form_company_placeholder': 'Your company name',
    'contact.form_service': 'Service of Interest',
    'contact.form_service_select': 'Select a service',
    'contact.form_service_conseil_commercial': 'Commercial Consulting and Optimization',
    'contact.form_service_rse_bilan': 'CSR Support / Carbon Footprint Assessment',
    'contact.form_message': 'Message *',
    'contact.form_message_placeholder': 'Describe your commercial optimization or CSR strategy project...',
    'contact.form_send': 'Send message',
    'contact.form_required': '* Required fields',
    'contact.success_title': 'Message sent!',
    'contact.success_message': 'We will contact you as soon as possible about your project.',
    
    // Expertise Section
    'expertise.title': 'Our Expertise',
    'expertise.subtitle': 'Since 2014, CRM Conseil has been supporting the growth of startups and micro-enterprises/SMEs committed to improving their commercial results. Take the next step today by making your sustainable transition a lever for commercial acceleration for the future.',
    'expertise.commercial_years': '26+ years',
    'expertise.commercial_experience': 'Commercial development and optimization',
    'expertise.commercial_desc': '• Sales and management of commercial teams in France and International\n• Field commercial optimization for startups and SMEs\n• Practical preparation for fundraising in Greentech, Deeptech, Agritech, Healthtech and Telecom sectors\n• Commercial optimization in Tourism sector.',
    'expertise.consulting_years': '5+ years',
    'expertise.consulting_experience': 'Sustainability consulting & CSR strategy',
    'expertise.consulting_desc': 'CSR support and enhancement of sustainable development strategies',
    'expertise.entrepreneurship': 'Entrepreneurship & Innovation',
    'expertise.entrepreneurship_desc': 'Multiple entrepreneurial experiences with creation and management of companies in digital, tourism and consulting, with a systematic approach to sustainability.',
    'expertise.certifications_title': 'Certifications & Training',
    'expertise.mit_title': 'MIT Sustainable Strategy',
    'expertise.mit_desc': 'Sustainable development strategy certification by the Massachusetts Institute of Technology',
    'expertise.ademe_title': 'ADEME Carbon Assessment®',
    'expertise.ademe_desc': 'ABC certification to conduct regulatory Carbon Assessments®.',
    'expertise.sales_title': 'Miller Heiman Sales Process',
    'expertise.sales_desc': 'Certification in Miller Heiman Strategic Selling methodology for Enterprise accounts',
    'expertise.mba_title': 'FIU/SKEMA Bachelor of Business Administration',
    'expertise.mba_desc': 'Bachelor in Business Management, Marketing and International Business from Florida International University and SKEMA France.',
    'expertise.methodologies': 'Methodologies & Tools',
    'expertise.commercial_optimization': 'Commercial Optimization',
    'expertise.rse_biodiversity': 'CSR, Biodiversity & Carbon Assessment®',
    'expertise.unique_approach': 'Our Unique Approach',
    'expertise.performance_sustainability': 'Performance & Sustainability',
    'expertise.performance_desc': 'We combine commercial excellence and sustainable strategies for responsible growth.',
    'expertise.sector_expertise': 'Innovation Sector Expertise',
    'expertise.sector_desc': 'Specialization in technological innovation: GreenTech, DeepTech, HealthTech and Digital.',
    'expertise.recognized_certifications': 'Recognized Certifications',
    'expertise.certifications_desc': 'MIT, Carbon Assessment® and Miller Heiman training for cutting-edge expertise in commercial performance and sustainability.',
    'expertise.discover_about': 'Discover our journey',
    
    // Portfolio Section
    'portfolio.title': 'Our References',
    'portfolio.subtitle': 'More than 100 startups and SMEs supported in their commercial optimization and CSR strategy',
    'portfolio.greentech': 'Greentech',
    'portfolio.greentech_desc': '',
    'portfolio.deeptech': 'Deeptech',
    'portfolio.deeptech_desc': '',
    'portfolio.healthtech': 'Devtech',
    'portfolio.healthtech_desc': '',
    'portfolio.digital': 'Tourism',
    'portfolio.digital_desc': '',
    'portfolio.partners': 'Our partners',

    // About page
    'about.page_title': 'About CRM Conseil - Commercial Performance & CSR Expert | Sabrina Broggini',
    'about.key_stats_title': 'Our Impact in Numbers',
    'about.stat_startups': 'Startups & SMEs supported',
    'about.stat_growth': 'Average commercial performance increase',
    'about.stat_csr_impact': 'Commercial impact of a CSR approach',
    'about.stat_sectors': 'Innovation sectors',
    'about.stat_funding': 'Funding optimization generated',
    'about.company_history': 'Our Story: From Commercial Optimization to Sustainable Development',
    'about.story_desc_1': 'Founded in 2014, CRM Conseil was born from the vision of combining commercial performance with sustainable development. Our expertise in business development and commercial optimization quickly positioned us as a key partner for innovative startups.',
    'about.story_desc_2': 'With deep expertise in GHG assessment and CSR strategy, we help companies transform their sustainability challenges into commercial performance levers.',
    'about.story_desc_3': 'Today, we support over 100 companies in their sustainable commercial development, combining lead generation optimization, performance commerciale enhancement, and durability strategy.',
    'about.method_title': 'Our Methodology: Commercial Performance & Sustainable Innovation',
    'about.method_subtitle': 'A proven approach combining business development, commercial optimization, and CSR strategy for maximum impact',
    'about.method_approach': 'Our unique methodology integrates commercial performance optimization with sustainable development strategy. We help startups and SMEs achieve their business development goals while building a strong CSR foundation.',
    'about.our_difference': 'What makes us different',
    'about.difference_desc_1': 'We are the only consultants combining GHG assessment expertise with proven commercial performance optimization methods.',
    'about.difference_desc_2': 'Result: sustainable commercial development that generates both revenue growth and positive environmental impact.',
    'about.no_theory_title': 'Concrete Action, Measurable Results',
    'about.no_theory_desc': 'No theoretical approaches. We implement operational solutions that deliver immediate results in commercial performance while building your CSR strategy for long-term sustainability.',
    'about.mission_flow_title': 'Our 4-Step Process for Commercial Optimization & CSR Development',
    'about.step_1_title': 'Commercial Diagnosis & CSR Assessment',
    'about.step_1_desc': 'Complete audit of your commercial processes and sustainability practices with GHG assessment methodology',
    'about.step_2_title': 'Strategy & Optimization Planning',
    'about.step_2_desc': 'Development of integrated plan combining business development optimization and CSR strategy implementation',
    'about.step_3_title': 'Implementation & Performance Enhancement',
    'about.step_3_desc': 'Deployment of commercial optimization tools and sustainable development practices with continuous performance monitoring',
    'about.step_4_title': 'Growth & Sustainability Acceleration',
    'about.step_4_desc': 'Scaling of optimized commercial processes and CSR strategy for accelerated sustainable growth',
    'about.external_audit': 'External Commercial & CSR Audit',
    'about.external_audit_step_1': 'Complete analysis of commercial processes and sustainability practices',
    'about.external_audit_step_2': 'GHG assessment and CSR strategy evaluation',
    'about.external_audit_step_3': 'Identification of business development and performance optimization opportunities',
    'about.external_audit_step_4': 'Recommendations for commercial optimization and sustainable development integration',
    'about.tools_config': 'Commercial Tools & CSR Systems Configuration',
    'about.tools_config_step_1': 'CRM and lead generation optimization setup',
    'about.tools_config_step_2': 'GHG tracking and CSR reporting systems implementation',
    'about.tools_config_step_3': 'Business development automation and performance dashboards',
    'about.tools_config_step_4': 'Sustainability KPIs integration with commercial metrics',
    'about.commercial_materials': 'Commercial Content & CSR Communication',
    'about.commercial_materials_step_1': 'Development of performance-oriented sales materials',
    'about.commercial_materials_step_2': 'Creation of CSR-focused value propositions',
    'about.commercial_materials_step_3': 'Sustainable development storytelling for commercial advantage',
    'about.commercial_materials_step_4': 'Lead generation content optimized for CSR-conscious prospects',
    'about.team_training': 'Team Training: Commercial Performance & CSR',
    'about.team_training_step_1': 'Commercial optimization and business development training',
    'about.team_training_step_2': 'CSR strategy and sustainable development awareness',
    'about.team_training_step_3': 'Lead generation and performance enhancement techniques',
    'about.team_training_step_4': 'Integration of sustainability in commercial processes',
    'about.carbon_assessment': 'GHG Assessment & Environmental Impact',
    'about.carbon_assessment_step_1': 'Complete GHG assessment',
    'about.carbon_assessment_step_2': 'Environmental impact analysis and reduction strategies',
    'about.carbon_assessment_step_3': 'CSR strategy development and sustainability roadmap',
    'about.carbon_assessment_step_4': 'Carbon neutrality planning and performance tracking',
    'about.biodiversity_assessment': 'Biodiversity Impact & Sustainable Innovation',
    'about.biodiversity_assessment_step_1': 'Biodiversity impact assessment and ecosystem analysis',
    'about.biodiversity_assessment_step_2': 'Sustainable innovation opportunities identification',
    'about.biodiversity_assessment_step_3': 'Green business development strategies',
    'about.biodiversity_assessment_step_4': 'Environmental performance optimization and reporting',
    'about.excellence_operational': 'Operational Excellence in Commercial Performance',
    'about.excellence_operational_desc': 'We deliver measurable results in commercial optimization, business development, and lead generation with proven methodologies and sustainable practices.',
    'about.innovation_continuous': 'Continuous Innovation & Sustainable Development',
    'about.innovation_continuous_desc': 'We integrate the latest innovations in commercial performance with cutting-edge CSR strategies and sustainable development practices.',
    'about.impact_sustainable': 'Sustainable Commercial Impact & Performance',
    'about.impact_sustainable_desc': 'Every commercial optimization project includes CSR strategy development to ensure long-term sustainability and positive environmental impact.',
    'about.year_2014': '2014',
    'about.year_2014_title': 'Foundation & Commercial Expertise',
    'about.year_2014_desc': 'Launch of CRM Conseil with focus on commercial optimization and business development for innovative startups.',
    'about.year_2018': '2018',
    'about.year_2018_title': 'CSR Integration & Sustainable Development',
    'about.year_2018_desc': 'Integration of CSR strategy and sustainable development services with GHG assessment expertise.',
    'about.year_2019': '2019',
    'about.year_2019_title': 'Performance Commerciale Leadership',
    'about.year_2019_desc': 'Recognition as leading expert in commercial performance optimization and sustainable business development.',
    'about.year_2024': '2024',
    'about.year_2024_title': 'Sustainable Innovation Leadership',
    'about.year_2024_desc': 'Market leader in combining commercial optimization with CSR strategy and sustainable development for startups and innovative SMEs.',
    'about.greentech': 'GreenTech & Sustainable Innovation',
    'about.greentech_desc': 'Commercial development and CSR strategy for clean technology startups and sustainable innovation companies.',
    'about.healthtech': 'HealthTech & Medical Innovation',
    'about.healthtech_desc': 'Business development optimization and sustainable practices for healthcare technology and medical innovation companies.',
    'about.industry': 'Industry 4.0 & Sustainable Manufacturing',
    'about.industry_desc': 'Commercial optimization and environmental performance enhancement for industrial companies and sustainable manufacturing.',
    'about.dev_ai': 'AI Development & Digital Innovation',
    'about.dev_ai_desc': 'Business development and CSR integration for artificial intelligence companies and digital innovation startups.',
    'about.certifications_title': 'Certifications & Strategic Partnerships',
    'about.mit_cert': 'MIT Commercial Excellence Certification',
    'about.mit_cert_desc': 'Advanced certification in commercial performance optimization and business development strategies.',
    'about.rse_expert': 'CSR Strategy Expert',
    'about.rse_expert_desc': 'Expert in GHG assessment and sustainable development consulting.',
    'about.pacte_national': 'National Pact for Sustainable Development',
    'about.pacte_national_desc': 'Member of national initiative for CSR strategy and sustainable commercial development.',

    // Services page
    'services.page_title': 'Commercial Optimization & CSR Services | Business Development & Sustainability',
    'services.page_description': 'Expert services in commercial optimization, business development, GHG assessment, and CSR strategy for startups and SMEs. Lead generation and sustainable performance.',
    'services.page_keywords': 'commercial optimization, business development, lead generation, CSR strategy, GHG assessment, sustainable development, performance commerciale, startup services',
    'services.quote': '"The future belongs to companies that <strong>combine commercial performance with sustainable development</strong>. Make your CSR commitment a competitive advantage."',
    'services.performance_sustainability': 'Commercial Performance',
    'services.ecological_sustainability': 'Ecological Sustainability',
    'services.discover_services': 'Discover Our Expertise in Commercial Optimization & Sustainable Development',
    'services.commercial_optimization_missions': 'Commercial Optimization & Business Development',
    'services.rse_support_bilans': 'CSR Strategy & GHG Assessment',
    'services.commercial_intro_1': 'Less than 40% of salespeople\'s time is dedicated to selling. CRM Conseil helps startups and SMEs eliminate bottlenecks, reduce their sales cycle, and maximize their commercial efficiency. Simplify your tools, perfect your pitches and prospect qualification, and achieve sustainable results.',
    'services.commercial_intro_2': 'We combine traditional commercial excellence with sustainable development principles to create lasting competitive advantages and measurable performance improvements.',
    'services.process_optimization_title': 'Commercial Process & Materials Optimization',
    'services.process_optimization_desc': 'Analysis and restructuring of your sales processes and materials, sales cycle improvement, support during strategic client meetings, optimization of lead and opportunity qualification to maximize your commercial efficiency. Your gains: Faster deal closing',
    'services.tools_configuration_title': 'CRM & Business Development Tools Configuration',
    'services.tools_configuration_desc': 'Selection and configuration of tools (CRM/ERP) adapted to your needs, budget and growth perspectives. CRM Conseil guides you towards the most scalable tools to avoid having to multiply or change tools as you develop. We train your teams and configure your commercial dashboards. Your gains: Weeks of analysis and months of inappropriate tool deployment saved.',
    'services.lead_generation_title': 'Outsourced B2B Lead Generation',
    'services.lead_generation_desc': 'Boost your pipeline in less than a month through our outsourced lead generation campaigns. We continuously feed your sales teams with highly qualified opportunities, so they spend less time prospecting… and focus on closing deals. Your gains: More leads, more signatures, faster!',
    'services.valorization_title': 'Fundraising Preparation',
    'services.valorization_desc': 'Boost your chances of convincing investors, funds and family offices with an ultra-designed pitch deck, solid valorization of your KPIs and model, an impactful executive pitch and personalized investor hooks. Everything you need to transform interest… into investment. Your gains: Increased fundraising success rate',
    'services.what_we_bring': 'Expected Results: Commercial Performance & Sustainable Development Impact',
    'services.phase_1_title': 'Targeting / First Customers Acquisition',
    'services.phase_1_subtitle': 'Immediate Performance Enhancement',
    'services.conversion_increase': 'Conversion rate increase',
    'services.cycle_acceleration': 'Sales cycle acceleration',
    'services.qualified_meetings': 'Qualified meetings increase',
    'services.phase_2_title': 'Acceleration / Fundraising',
    'services.phase_2_subtitle': 'Sustainable Growth Acceleration',
    'services.pipeline_value_increase': 'Pipeline value increase',
    'services.commercial_efficiency': 'Commercial efficiency multiplication',
    'services.customer_satisfaction': 'Customer satisfaction improvement',
    'services.deliverables_title': 'Deliverables & Commercial Performance Reports',
    'services.deliverable_1': 'Quantified commercial performance analysis report',
    'services.deliverable_2': 'Business development optimization roadmap',
    'services.deliverable_3': 'Lead generation strategy implementation guide',
    'services.deliverable_4': 'Commercial team training and performance enhancement plan',
    'services.pricing_info': 'Investment: From €2,500 to €8,000 depending on company size and business development complexity',
    'services.rse_enhancement': 'CSR Strategy & Sustainable Development Enhancement',
    'services.rse_intro_1': 'Our CSR expertise combines GHG assessment with strategic sustainable development planning to create competitive commercial advantages.',
    'services.rse_intro_2': 'We help companies transform their sustainability commitments into powerful business development tools and commercial performance drivers.',
    'services.scope_1_title': 'GHG Sustainability / Carbon Assessment®',
    'services.scope_1_desc': 'GHG or Carbon Assessment® analyzes all your carbon emissions, including an analysis of climate risks facing your company and the climate impacts you generate, and defines a more sustainable transition plan. This voluntary approach allows repositioning your company in a valuable sustainability approach. Your gains: reduction of your costs and carbon energy dependency, development of new markets, enhanced attractiveness to talent and investors.',
    'services.scope_123_title': 'Implementation, monitoring and training of teams on sustainable actions',
    'services.scope_123_desc': 'The success of a company transition towards more sustainable approaches necessarily involves awareness and team engagement. Managers are often helpless about operational team management on these actions, facing certain resistance to change. CRM Conseil offers support on implementing the defined sustainability strategy, with not only objective monitoring support, but also motivational training on essential sustainability actions related to each business sector. Your gains: engaged teams and concrete objectives met',
    'services.biodiversity_title_services': 'Commercial value of CSR approach',
    'services.biodiversity_desc_services': 'CRM Conseil rightly considers that a company\'s commitment to sustainability brings real commercial and financial returns. We model the ROI of your actions over several years in terms of cost reductions, product repositioning, and new markets. We manage lead generation campaigns for our clients in these new markets, allowing quick validation of commercial returns. Your gains: ROI of sustainability approach and increased results',
    'services.rse_results_title': 'Expected Results & ROI: CSR Strategy Impact',
    'services.carbon_reduction': 'GHG emissions reduction',
    'services.csr_positioning': 'CSR market positioning improvement',
    'services.sustainability_roi': 'Sustainability ROI increase',
    'services.regulatory_compliance': 'Regulatory compliance achievement',
    'services.brand_value': 'Sustainable brand value enhancement',
    'services.market_differentiation': 'Market differentiation through CSR',
    'services.rse_deliverables_title': 'CSR Strategy Deliverables & Sustainable Development Reports',
    'services.rse_deliverable_1': 'GHG assessment analysis report',
    'services.rse_deliverable_2': 'Complete CSR strategy and sustainable development roadmap',
    'services.rse_deliverable_3': 'Team training on sustainability and commercial performance integration',
    'services.rse_deliverable_4': 'Ongoing support and performance monitoring system',
    'services.rse_pricing': 'Investment: From €3,500 to €15,000 (subsidies up to 70% available through ADEME and regional programs)',
    'services.transform_business': 'Transform Your Business with Sustainable Commercial Performance',
    'services.transform_subtitle': 'Ready to optimize your commercial performance while building a strong CSR strategy?',
    'services.book_appointment': 'Book Your Strategic Consultation',
    'services.contact_us': 'Contact Our Experts',
    
    // Additional About page translations - commitments and pillars
    'about.commitments_title': 'Our CSR Commitments',
    'about.commitments_intro': 'At CRM Conseil, we practice what we preach by implementing concrete CSR actions organized around 4 strategic pillars.',
    'about.pillar_1_title': 'Clients & CSR Strategy',
    'about.pillar_1_item_1': 'Prioritize low-carbon clients aligned with CSR values',
    'about.pillar_1_item_2': 'Support eco-responsible companies in their sustainable development',
    'about.pillar_1_item_3': 'Develop commercial partnerships with certified sustainable businesses',
    'about.pillar_2_title': 'Sustainable Transport',
    'about.pillar_2_item_1': 'Electric vehicle for all client visits within a 50km radius',
    'about.pillar_2_item_2': 'Public transport for trips exceeding 50km when possible',
    'about.pillar_2_item_3': 'Carbon offsetting for unavoidable flights through certified programs',
    'about.pillar_3_title': 'Clean Energy Sourcing',
    'about.pillar_3_item_1': '100% renewable energy for our offices',
    'about.pillar_3_item_2': 'Green energy suppliers certified by responsible energy labels',
    'about.pillar_3_item_3': 'Digital GHG optimization through eco-designed tools',
    'about.pillar_3_item_4': 'Energy-efficient equipment and responsible consumption practices',
    'about.pillar_4_title': 'Waste Management',
    'about.pillar_4_item_1': 'Systematic waste sorting and recycling in offices',
    'about.pillar_4_item_2': 'Paperless office policy and digital document management',
    'about.pillar_4_item_3': 'Partnership with local recycling and reuse circuits',
    'about.transform_sustainably': 'Ready to transform your business sustainably?',
    'about.transform_desc': 'Discover how we can support you in your growth while integrating a high-performance CSR approach.',
    'about.book_consultation': 'Book a consultation',
    'about.contact_us': 'Contact us',
    
    // Additional Services page translations - deliverables and pricing
    'services.deliverables': 'Our deliverables',
    'services.deliverable_1_rse': 'Quantified carbon analysis report valuable at ADEME level',
    'services.deliverable_2_rse': 'Quantified CSR assessment and strategy report with ROI',
    'services.deliverable_3_rse': 'Quantified Biodiversity Impact Report',
    'services.deliverable_4_rse': 'Team training on CSR strategy',
    'services.deliverable_5': '5 - 15 person-days ~ €6,000 to €12,000 with possibility of BPI France subsidies of 40 to 50%, if eligible',
    'services.pricing_commercial': '5 - 15 person-days ~ €6,000 to €12,000 with possibility of BPI France subsidies of 40 to 50%, if eligible',
    
    // Contact form confirmation messages
    'contact.success_toast_title': 'Message sent successfully!',
    'contact.success_toast_description': 'Thank you for your message. We will respond to you as soon as possible.',
    'contact.error_toast_title': 'Submission error',
    'contact.error_toast_description': 'An error occurred while sending your message. Please try again or contact us directly.',
    'contact.error_validation_title': 'Required fields missing',
    'contact.error_validation_description': 'Please fill in all required fields.',
    'contact.sending': 'Sending...',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('preferred-language');
    const browserLanguage = navigator.language.startsWith('fr') ? 'fr' : 'en';
    return (savedLanguage as Language) || browserLanguage;
  });

  useEffect(() => {
    localStorage.setItem('preferred-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};